version: "3.8"

services:  
  example:
    container_name: docker-example-py
    image: ghcr.io/karikolehmainen/docker-example-py:latest
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=6000
    ports:
      - 5001:6000
    networks:
      - internal-network

networks:
    internal-network:
      driver: bridge
